<?php declare(strict_types = 1);

/*
 * This file is part of the Valksor package.
 *
 * (c) Davis Zalitis (k0d3r1s)
 * (c) SIA Valksor <packages@valksor.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Doctrine\Migrations {
    if (!class_exists(AbstractMigration::class, autoload: false)) {
        abstract class AbstractMigration
        {
        }
    }
}

namespace ValksorDev\PhpCsFixerCustomFixers\Tests {
    use ValksorDev\PhpCsFixerCustomFixers\Fixer\DoctrineMigrationsFixer;

    final class DoctrineMigrationsFixerTest extends AbstractFixerTestCase
    {
        public function testRemovesAutoGeneratedComments(): void
        {
            $input = <<<'PHP'
                <?php declare(strict_types=1);

                namespace App\Migration;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                /**
                 * Auto-generated Migration: Please modify to your needs!
                 */
                final class VersionTest extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        // this up() migration is auto-generated, please modify it to your needs
                        $schema->createTable('foo');
                    }

                    public function down(Schema $schema): void
                    {
                        // this down() migration is auto-generated, please modify it to your needs
                        $schema->dropTable('foo');
                    }
                }
                PHP;

            $expected = <<<'PHP'
                <?php declare(strict_types=1);

                namespace App\Migration;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                final class VersionTest extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        $schema->createTable('foo');
                    }

                    public function down(Schema $schema): void
                    {
                        $schema->dropTable('foo');
                    }
                }
                PHP;

            $this->assertFixerCodeSame(new DoctrineMigrationsFixer(), $expected . "\n", $input . "\n");
        }
    }
}
